import Head from 'next/head';
import HomeTwoMain from '../components/HomeTwo/HomeTwoMain';
import Footer from '../components/Layout/Footer/FooterOne/Footer';
import HeaderTwo from '../components/Layout/Header/HeaderTwo/HeaderTwo';


export default function HomeTwo() {

  return (
    <>
      <Head>
        <title>Eduman - Education And Online Courses React, NextJs Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
       <HeaderTwo />
      <HomeTwoMain />
      <Footer />
    </>
  )
}
