import Head from 'next/head';
import HomeThreeMain from '../components/HomeThree/HomeThreeMain';
import FooterTwo from '../components/Layout/Footer/FooterTwo/FooterTwo';
import HeaderThree from '../components/Layout/Header/HeaderThree/HeaderThree';


export default function HomeThree() {

  return (
    <>
      <Head>
        <title>Eduman - Education And Online Courses React, NextJs Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
       <HeaderThree />
      <HomeThreeMain />
      <FooterTwo />
      
    </>
  )
}
